<header id="top">
    <!--1-1.로고박스-->
    <h1 id="logo">
        <!--글자-->
        <img id="mtit" src="images/mlogo_7.png" alt="my items">
        <!--빨간공-->
        <img id="rb" src="images/mlogo_6.png" alt="빨간공">
        <!--카멜레온박스-->
        <div id="cb">
            <!--혀박스-->
            <span id="tung"></span>
            <!--카멜레온-->
            <img id="cam" src="images/mlogo_05.png" alt="카멜레온">
        </div>

    </h1>
    <!--1-2.공통메뉴-->
    <ul class="tmenu">
        <li>
            <a href="">회원가입</a>
        </li>
        <li>
            <a href="">로그인</a>
        </li>
        <li>
            <a href="">게시판</a>
        </li>
        <li>
            <a href="">오시는길</a>
        </li>
    </ul>
    <!--1-3.SNS메뉴-->
    <ul class="sns">
        <li>
            <a href="">
                <span class="bld">트위터</span>
            </a>
        </li>
        <li>
            <a href="">
                <span class="bld">인스타그램</span>
            </a>
        </li>
        <li>
            <a href="">
                <span class="bld">페이스북</span>
            </a>
        </li>
    </ul>
    <!--1-4.GNB메뉴-->
    <nav class="gnb">
        <ul>
            <li>
                <a href="">Home</a>
            </li>
            <li>
                <a href="">디바이스</a>
                <ol class="smenu">
                    <li>
                        <a href="">
                            스마트폰
                        </a>
                    </li>
                    <li>
                        <a href="">
                            태블릿PC
                        </a>
                    </li>
                    <li>
                        <a href="">
                            노트북
                        </a>
                    </li>
                </ol>
            </li>
            <li>
                <a href="">패션</a>
                <ol class="smenu">
                    <li>
                        <a href="">
                            가방
                        </a>
                    </li>
                    <li>
                        <a href="">
                            시계
                        </a>
                    </li>
                    <li>
                        <a href="">
                            구두
                        </a>
                    </li>
                </ol>
            </li>
            <li>
                <a href="">프로필</a>
            </li>
        </ul>
    </nav>
</header>