
<footer class="info ibx">
    <!-- 3-1. 하단로고 -->
    <div class="blogo">
        <img src="images/footer_logo.png" alt="하단로고">
    </div>
    <!-- 3-2. 회사주소 -->
    <address class="addr">
        WWW.VOGUE.COM Ⓒ CONDÉNAST ASIA PACIFIC. INC. ALL RIGHTS RESERVED. VOGUE.COM KOREA IS OPERATED BY DOOSAN MAGAZINE.
    </address>
    <!-- 3-3. 하단링크 -->
    <ul class="blink">
        <li>
            <a href="#">정기구독</a>
        </li>
        <li>
            <a href="#">회사소개</a>
        </li>
        <li>
            <a href="#">광고 및 제휴</a>
        </li>
        <li>
            <a href="#">개인정보 처리방침</a>
        </li>
    </ul>
</footer>


<!-- 위로가기 버튼 -->
<a href="#" class="tbtn fi fi-angle-up">
    <span class="ir">위로가기버튼</span>
</a>
