
<header class="top ibx">
    <!-- 1-1.상단메뉴 -->
    <div class="tmenu">
        <!-- 1-1-1.sns박스 -->
        <div class="sns">
            <a href="#" class="fi fi-instagram">
                <span class="ir">
                    인스타그램
                </span>
            </a>
            <a href="#" class="fi fi-facebook">
                <span class="ir">
                    페이스북
                </span>
            </a>
            <a href="#" class="fi fi-twitter">
                <span class="ir">
                    트위터
                </span>
            </a>
            <a href="#" class="fi fi-youtube-play">
                <span class="ir">
                    유튜브
                </span>
            </a>
            <a href="#">
                <span class="ir">
                    카카오스토리
                </span>
            </a>
        </div>
        <!-- 1-1-2.사이드메뉴 -->
        <div class="sideMenu">
            <ul class="smbx">
                <li>
                    <a href="#">SIDE MENU</a>
                    <!-- 서브메뉴 -->
                    <ol class="smsub">
                        <li>
                            <a href="#">회사 소개</a>
                        </li>
                        <li>
                            <a href="login.php">보그 로그인</a>
                        </li>
                        <li>
                            <a href="member.php">보그 회원가입</a>
                        </li>
                    </ol>
                </li>
                <li>
                    <a href="#">SUBSCRIBE</a>
                </li>
            </ul>
        </div>
    </div>

    <!-- 1-2.로고박스 -->
    <h1 class="logo">
        <a href="#">
            <img src="images/mlogo.png" alt="메인로고">
        </a>
    </h1>
    <!-- 1-3.GNB박스 -->
    <nav class="gnb">
        <ul>
            <li>
                <a href="#">FASHION</a>
            </li>
            <li>
                <a href="#">BEAUTY</a>
            </li>
            <li>
                <a href="#">LIVING</a>
            </li>
            <li>
                <a href="#">PEOPLE</a>
            </li>
            <li>
                <a href="#">VIDEO</a>
            </li>
            <li>
                <a href="#">RUNWAY</a>
            </li>
            <li>
                <a href="#">SHOPPING</a>
            </li>
            <li>
                <a href="#" class="fi fi-search">
                    <span class="ir">search</span>
                </a>
            </li>
        </ul>
    </nav>
    
    <!-- 모바일용 햄버거버튼 -->
    <a href="#" class="mobtn hbtn fi fi-nav-icon">
        <span class="ir">GNB button</span>
    </a>
    <!-- 모바일용 검색버튼 -->
    <a href="#" class="mobtn sbtn fi fi-search">
        <span class="ir">search</span>
    </a>
</header>

<!-- 1.4.모바일 검색박스 -->
<div class="mos">
    <div class="mwrap">
        <!-- 입력창박스 -->
        <div id="search">
            <input type="text" class="search">
        </div>
        <!-- 검색버튼 -->
        <button class="scbtn fi fi-search">
            <span class="ir">돋보기검색아이콘</span>
        </button>
    </div>
</div>

<!-- 1.5.모바일 전체메뉴 -->
<div id="mobx">
    <!-- 1.5-1.모바일 GNB 메뉴 -->
    <nav class="mognb">
        <ul>
            <li>
                <a href="#">FASHION</a>
            </li>
            <li>
                <a href="#">BEAUTY</a>
            </li>
            <li>
                <a href="#">LIVING</a>
            </li>
            <li>
                <a href="#">PEOPLE</a>
            </li>
            <li>
                <a href="#">VIDEO</a>
            </li>
            <li>
                <a href="#">RUNWAY</a>
            </li>
            <li>
                <a href="#">SHOPPING</a>
            </li>
        </ul>
    </nav>
    <!-- 1.5-2.모바일 sns 메뉴 -->
    <div class="mosns">
        <a href="#" class="fi fi-instagram">
            <span class="ir">인스타그램</span>
        </a>
        <a href="#" class="fi fi-facebook">
            <span class="ir">페이스북</span>
        </a>
        <a href="#" class="fi fi-twitter">
            <span class="ir">트위터</span>
        </a>
        <a href="#" class="fi fi-youtube-play">
            <span class="ir">유튜브</span>
        </a>
        <a href="#">
            <span class="ir">카카오스토리</span>
        </a>

    </div>
    <!-- 1.5-3.매거진박스 -->
    <figure class="magbox">
        <!-- 잡지커버이미지 -->
        <a class="mcover" href="#">
            <img src="./images/cover.jpg" alt="보그표지">
        </a>
        <!-- 잡지설명 -->
        <figcaption>
            정기구독을 신청하면 최대 30% 할인혜택을 드립니다!
        </figcaption>
        <!-- 정기구독버튼 -->
        <button class="magbtn">정기구독 신청</button>
    </figure>

    <!-- 하단링크박스 -->
    <ul class="moblink">
        <li>
            <a href="#">회사소개 /</a>
        </li>
        <li>
            <a href="#">광고 및 제휴 /</a>
        </li>
        <li>
            <a href="#">
                <strong>개인정보 처리방침</strong>
            </a>
        </li>
    </ul>
</div>
<!-- 모바일용 메뉴 끝 -->

